let date=new Date()
console.log( typeof date)
console.log(date.toString())
console.log(date.toDateString())
let mycreated = new Date(2026,7,12)
console.log(mycreated)
let mytimestamp = Date.now()
console.log(mytimestamp)
console.log(mycreated.getTime())